.TH GIT-RESTORE-MTIME-CORE 1 2016-01-31
.\" For nroff, turn off justification.  Always turn off hyphenation; it makes
.\" way too many mistakes in technical documents.
.if n .ad l
.nh
.SH NAME
git-restore-mtime-core \-
Restore original modification time of files based on the date of the most
recent commit that modified them
.SH SYNOPSIS
.B git-restore-mtime-core
.RB [ -h ]
.RB [ --verbose ]
.RB [ --merge ]
.RI [ pathspec
.RI [ pathspec ...]]
.SH DESCRIPTION
Restore original modification time of files based on the date of the most
recent commit that modified them. Useful when generating release tarballs.
Current directory must be inside work tree.
.SH OPTIONS
.SS Positional arguments:
.TP 8
.I pathspec
only modify paths (dirs or files) matching PATHSPEC,
absolute or relative to current directory. Default is
current directory.
.SS Optional arguments:
.TP 8
.BR \-h , \ \-\-help
show help message and exit
.TP 8
.BR \-\-verbose , \-v
print warnings and debug info for each processed file.
.TP 8
.BR \-\-merge , \-m
include merge commits.
.SH SEE ALSO
.B https://github.com/MestreLion/git-tools
.SH AUTHOR
Rodrigo Silva (MestreLion) linux@rodrigosilva.com
